### Voir Wilders

GET http://localhost:3000/api/wilder

### Ajouter Wilder

POST http://localhost:3000/api/wilder
Content-Type: application/json

{
    "name": "Jane Doe"
}

### Supprimer Wilder

DELETE http://localhost:3000/api/wilder/10

### Modifier Wilder

PUT http://localhost:3000/api/wilder/10
Content-Type: application/json

{   
    "name": "Jane Doe 2"
}

### Ajouter Skill Wilder

POST http://localhost:3000/api/wilder/4/skill/1

